#include <Windows.h>
#include <CommCtrl.h>
#include <ShlObj.h>
#include <shellapi.h>
#include <objbase.h>
#include <sddl.h>
#include <Windowsx.h>
#include <algorithm>
#include <filesystem>
#include <memory>
#include "../domain/model.h"
#include "../application/snippet_service.h"
#include "../infrastructure/settings_repository.h"
#include "../infrastructure/win32_services.h"
#include "../infrastructure/file_logger.h"
#pragma comment(lib,"comctl32.lib")
#pragma comment(lib,"shell32.lib")
#pragma comment(lib,"advapi32.lib")
using namespace snippet;
namespace {
constexpr UINT WM_TRAY=WM_APP+1; constexpr UINT_PTR INPUT_TIMER=7; constexpr int PICKER_HOTKEY_ID=0x7FFE;
enum Id {List=100,Name,Body,HotkeyControl,Enabled,Save,NewItem,Remove,Startup,Status,PickerList,PickerHotkeyControl,PickerWin,SavePickerHotkey};
UINT showMessage{},taskbarMessage{};
std::wstring Guid(){GUID g{};if(FAILED(CoCreateGuid(&g)))return L"";wchar_t text[40]{};if(StringFromGUID2(g,text,40)==0)return L"";return text;}
std::filesystem::path TestRoot(){std::vector<wchar_t> value(32768);const DWORD n=GetEnvironmentVariableW(L"SNIPPETTOOL_TEST_ROOT",value.data(),static_cast<DWORD>(value.size()));return n>0&&n<value.size()?std::filesystem::path(value.data()):std::filesystem::path{};}
std::wstring ExePath(){std::wstring p(32768,L'\0');const DWORD n=GetModuleFileNameW(nullptr,p.data(),static_cast<DWORD>(p.size()));p.resize(n);return p;}
std::filesystem::path SettingsPath(){if(const auto test=TestRoot();!test.empty())return test/L"settings.xml";return std::filesystem::path(ExePath()).parent_path()/L"settings.xml";}
std::wstring MutexName(){HANDLE token{};if(!OpenProcessToken(GetCurrentProcess(),TOKEN_QUERY,&token))return L"Local\\SnippetTool";DWORD bytes{};GetTokenInformation(token,TokenUser,nullptr,0,&bytes);std::vector<BYTE> data(bytes);if(!GetTokenInformation(token,TokenUser,data.data(),bytes,&bytes)){CloseHandle(token);return L"Local\\SnippetTool";}LPWSTR sid{};const auto* user=reinterpret_cast<TOKEN_USER*>(data.data());ConvertSidToStringSidW(user->User.Sid,&sid);std::wstring name=L"Local\\SnippetTool-"+std::wstring(sid?sid:L"user");if(sid)LocalFree(sid);CloseHandle(token);return name;}
UINT ModifiersFromHotkeyWord(WORD value){UINT m{};const BYTE flags=HIBYTE(value);if(flags&HOTKEYF_CONTROL)m|=MOD_CONTROL;if(flags&HOTKEYF_ALT)m|=MOD_ALT;if(flags&HOTKEYF_SHIFT)m|=MOD_SHIFT;return m;}
Hotkey DomainHotkey(WORD value){Hotkey h;const UINT m=ModifiersFromHotkeyWord(value);if(m&MOD_CONTROL)h.modifiers.push_back(Modifier::Ctrl);if(m&MOD_ALT)h.modifiers.push_back(Modifier::Alt);if(m&MOD_SHIFT)h.modifiers.push_back(Modifier::Shift);h.virtualKey=LOBYTE(value);return h;}
WORD ControlHotkey(const Hotkey& h){BYTE f{};const auto m=ModifierMask(h);if(m&1)f|=HOTKEYF_CONTROL;if(m&2)f|=HOTKEYF_ALT;if(m&4)f|=HOTKEYF_SHIFT;return MAKEWORD(h.virtualKey,f);}
UINT NativeModifiers(const Hotkey& hotkey){UINT result=MOD_NOREPEAT;const auto mask=ModifierMask(hotkey);if(mask&1)result|=MOD_CONTROL;if(mask&2)result|=MOD_ALT;if(mask&4)result|=MOD_SHIFT;if(mask&8)result|=MOD_WIN;return result;}
class App {
public:
 int Run(HINSTANCE instance,int show);
private:
 static LRESULT CALLBACK WindowProc(HWND,UINT,WPARAM,LPARAM); LRESULT Handle(UINT,WPARAM,LPARAM);
 static LRESULT CALLBACK PickerProc(HWND,UINT,WPARAM,LPARAM); LRESULT HandlePicker(UINT,WPARAM,LPARAM);
 void BuildUi();void BuildPicker();void Refresh();void Select(int);void SaveCurrent();void RemoveCurrent();void UpdateStartup();void UpdatePickerHotkey();void SetStatus(const std::wstring&);void AddTray();void Show();void ShowPicker();void HidePicker();void ChoosePickerItem();void BeginInput(const Snippet*);
 HINSTANCE instance_{};HWND window_{},list_{},name_{},body_{},hotkey_{},win_{},enabled_{},startup_{},status_{},picker_{},pickerList_{},pickerHotkey_{},pickerWin_{};int selected_{-1};bool loadErrorLocked_{},pickerHotkeyRegistered_{};AppSettings settings_;std::vector<const Snippet*> pickerItems_;std::unique_ptr<XmlSettingsRepository> repository_;std::unique_ptr<HotkeyRegistry> hotkeys_;std::unique_ptr<SnippetService> service_;std::unique_ptr<FileLogger> logger_;StartupManager startupManager_;NOTIFYICONDATAW tray_{sizeof(tray_)};HWND inputTarget_{};const Snippet* pending_{};unsigned timerTicks_{};
};
int App::Run(HINSTANCE instance,int show){instance_=instance;INITCOMMONCONTROLSEX common{sizeof(common),ICC_LISTVIEW_CLASSES|ICC_WIN95_CLASSES};InitCommonControlsEx(&common);const auto settingsPath=SettingsPath();repository_=std::make_unique<XmlSettingsRepository>(settingsPath);logger_=std::make_unique<FileLogger>(settingsPath.parent_path()/L"logs"/L"app.log");auto loaded=repository_->Load();if(loaded.settings)settings_=*loaded.settings;
 WNDCLASSEXW wc{sizeof(wc)};wc.hInstance=instance;wc.lpfnWndProc=WindowProc;wc.lpszClassName=L"SnippetTool.Main";wc.hIcon=LoadIconW(nullptr,IDI_APPLICATION);wc.hCursor=LoadCursorW(nullptr,IDC_ARROW);wc.hbrBackground=reinterpret_cast<HBRUSH>(COLOR_WINDOW+1);RegisterClassExW(&wc);window_=CreateWindowExW(0,wc.lpszClassName,L"スニペットツール",WS_OVERLAPPEDWINDOW,CW_USEDEFAULT,CW_USEDEFAULT,760,575,nullptr,nullptr,instance,this);if(!window_)return 2;hotkeys_=std::make_unique<HotkeyRegistry>(window_);service_=std::make_unique<SnippetService>(settings_,*repository_,*hotkeys_);BuildUi();BuildPicker();pickerHotkeyRegistered_=RegisterHotKey(window_,PICKER_HOTKEY_ID,NativeModifiers(settings_.pickerHotkey),settings_.pickerHotkey.virtualKey)!=FALSE;const auto keyError=hotkeys_->Apply(settings_);Refresh();if(!loaded.error.empty()){loadErrorLocked_=true;SetStatus(loaded.error+L" 元ファイルを保護するため編集をロックしました。");if(TestRoot().empty()&&MessageBoxW(window_,L"設定ファイルが破損しています。元ファイルを .corrupt へ退避して初期化しますか？",L"設定読込エラー",MB_YESNO|MB_ICONERROR)==IDYES){std::error_code ec;auto backup=settingsPath;backup+=L".corrupt";std::filesystem::remove(backup,ec);std::filesystem::rename(settingsPath,backup,ec);if(!ec&&repository_->Save(settings_).empty()){loadErrorLocked_=false;SetStatus(L"破損設定を退避して初期化しました。");}}}else if(!pickerHotkeyRegistered_)SetStatus(FormatHotkey(settings_.pickerHotkey)+L" を登録できません (HOTKEY-REG-001)。");else if(!keyError.empty())SetStatus(keyError);AddTray();
 bool startupReady=true;if(loaded.error.empty()&&TestRoot().empty()){const auto e=settings_.startupEnabled?startupManager_.Enable(ExePath()):startupManager_.Disable(ExePath());if(!e.empty()){startupReady=false;SetStatus(e);}}if(loaded.error.empty()&&startupReady&&!settings_.firstRunCompleted){settings_.firstRunCompleted=true;const auto save=repository_->Save(settings_);if(!save.empty()){settings_.firstRunCompleted=false;if(TestRoot().empty()){const auto ignored=startupManager_.Disable(ExePath());(void)ignored;}SetStatus(save);}else if(TestRoot().empty())MessageBoxW(window_,L"スタートアップへ登録しました。本文は平文保存され、機密入力欄にも送信され得ます。",L"スニペットツール",MB_OK|MB_ICONINFORMATION);}
 const bool background=wcsstr(GetCommandLineW(),L"--background")!=nullptr;if(!background)ShowWindow(window_,show);MSG msg{};while(GetMessageW(&msg,nullptr,0,0)>0){if(IsWindowVisible(picker_)&&msg.message==WM_KEYDOWN){if(msg.wParam==VK_RETURN){ChoosePickerItem();continue;}if(msg.wParam==VK_ESCAPE){HidePicker();continue;}}TranslateMessage(&msg);DispatchMessageW(&msg);}return static_cast<int>(msg.wParam);}
LRESULT CALLBACK App::WindowProc(HWND w,UINT m,WPARAM p,LPARAM l){App* self=reinterpret_cast<App*>(GetWindowLongPtrW(w,GWLP_USERDATA));if(m==WM_NCCREATE){self=static_cast<App*>(reinterpret_cast<CREATESTRUCTW*>(l)->lpCreateParams);self->window_=w;SetWindowLongPtrW(w,GWLP_USERDATA,reinterpret_cast<LONG_PTR>(self));}try{return self?self->Handle(m,p,l):DefWindowProcW(w,m,p,l);}catch(...){MessageBoxW(w,L"予期しないエラーが発生しました。アプリを終了します。",L"スニペットツール",MB_OK|MB_ICONERROR);DestroyWindow(w);return 0;}}
LRESULT CALLBACK App::PickerProc(HWND w,UINT m,WPARAM p,LPARAM l){App* self=reinterpret_cast<App*>(GetWindowLongPtrW(w,GWLP_USERDATA));if(m==WM_NCCREATE){self=static_cast<App*>(reinterpret_cast<CREATESTRUCTW*>(l)->lpCreateParams);self->picker_=w;SetWindowLongPtrW(w,GWLP_USERDATA,reinterpret_cast<LONG_PTR>(self));}return self?self->HandlePicker(m,p,l):DefWindowProcW(w,m,p,l);}
void App::BuildUi(){list_=CreateWindowExW(WS_EX_CLIENTEDGE,WC_LISTVIEWW,L"",WS_CHILD|WS_VISIBLE|LVS_REPORT|LVS_SINGLESEL,10,10,720,180,window_,reinterpret_cast<HMENU>(List),instance_,nullptr);ListView_SetExtendedListViewStyle(list_,LVS_EX_FULLROWSELECT|LVS_EX_GRIDLINES);const wchar_t* heads[]={L"名称",L"ショートカット",L"有効",L"登録状態"};int widths[]={250,180,70,180};for(int i=0;i<4;++i){LVCOLUMNW c{LVCF_TEXT|LVCF_WIDTH};c.pszText=const_cast<LPWSTR>(heads[i]);c.cx=widths[i];ListView_InsertColumn(list_,i,&c);}
 CreateWindowW(L"STATIC",L"名称",WS_CHILD|WS_VISIBLE,10,205,80,25,window_,nullptr,instance_,nullptr);name_=CreateWindowExW(WS_EX_CLIENTEDGE,L"EDIT",L"",WS_CHILD|WS_VISIBLE|ES_AUTOHSCROLL,100,202,400,25,window_,reinterpret_cast<HMENU>(Name),instance_,nullptr);
 CreateWindowW(L"STATIC",L"本文",WS_CHILD|WS_VISIBLE,10,240,80,25,window_,nullptr,instance_,nullptr);body_=CreateWindowExW(WS_EX_CLIENTEDGE,L"EDIT",L"",WS_CHILD|WS_VISIBLE|ES_MULTILINE|ES_AUTOVSCROLL|WS_VSCROLL,100,237,630,100,window_,reinterpret_cast<HMENU>(Body),instance_,nullptr);
 CreateWindowW(L"STATIC",L"ショートカット",WS_CHILD|WS_VISIBLE,10,352,105,25,window_,nullptr,instance_,nullptr);hotkey_=CreateWindowExW(0,HOTKEY_CLASSW,L"",WS_CHILD|WS_VISIBLE|WS_BORDER,120,347,220,27,window_,reinterpret_cast<HMENU>(HotkeyControl),instance_,nullptr);SendMessageW(hotkey_,HKM_SETRULES,HKCOMB_NONE|HKCOMB_S,HOTKEYF_CONTROL);
 win_=CreateWindowW(L"BUTTON",L"Win",WS_CHILD|WS_VISIBLE|BS_AUTOCHECKBOX,350,348,65,25,window_,nullptr,instance_,nullptr);enabled_=CreateWindowW(L"BUTTON",L"有効",WS_CHILD|WS_VISIBLE|BS_AUTOCHECKBOX,420,348,70,25,window_,reinterpret_cast<HMENU>(Enabled),instance_,nullptr);startup_=CreateWindowW(L"BUTTON",L"サインイン時に起動",WS_CHILD|WS_VISIBLE|BS_AUTOCHECKBOX,500,348,180,25,window_,reinterpret_cast<HMENU>(Startup),instance_,nullptr);
 CreateWindowW(L"STATIC",L"ミニ画面表示キー",WS_CHILD|WS_VISIBLE,10,389,110,25,window_,nullptr,instance_,nullptr);pickerHotkey_=CreateWindowExW(0,HOTKEY_CLASSW,L"",WS_CHILD|WS_VISIBLE|WS_BORDER,120,384,220,27,window_,reinterpret_cast<HMENU>(PickerHotkeyControl),instance_,nullptr);SendMessageW(pickerHotkey_,HKM_SETRULES,HKCOMB_NONE|HKCOMB_S,HOTKEYF_ALT);SendMessageW(pickerHotkey_,HKM_SETHOTKEY,ControlHotkey(settings_.pickerHotkey),0);pickerWin_=CreateWindowW(L"BUTTON",L"Win",WS_CHILD|WS_VISIBLE|BS_AUTOCHECKBOX,350,385,65,25,window_,reinterpret_cast<HMENU>(PickerWin),instance_,nullptr);Button_SetCheck(pickerWin_,(ModifierMask(settings_.pickerHotkey)&8)?BST_CHECKED:BST_UNCHECKED);CreateWindowW(L"BUTTON",L"表示キーを保存",WS_CHILD|WS_VISIBLE,430,382,140,30,window_,reinterpret_cast<HMENU>(SavePickerHotkey),instance_,nullptr);
 CreateWindowW(L"BUTTON",L"新規",WS_CHILD|WS_VISIBLE,100,425,90,30,window_,reinterpret_cast<HMENU>(NewItem),instance_,nullptr);CreateWindowW(L"BUTTON",L"保存",WS_CHILD|WS_VISIBLE,200,425,90,30,window_,reinterpret_cast<HMENU>(Save),instance_,nullptr);CreateWindowW(L"BUTTON",L"削除",WS_CHILD|WS_VISIBLE,300,425,90,30,window_,reinterpret_cast<HMENU>(Remove),instance_,nullptr);status_=CreateWindowW(L"STATIC",L"",WS_CHILD|WS_VISIBLE,10,475,720,35,window_,reinterpret_cast<HMENU>(Status),instance_,nullptr);Button_SetCheck(startup_,settings_.startupEnabled?BST_CHECKED:BST_UNCHECKED);}
void App::BuildPicker(){WNDCLASSEXW wc{sizeof(wc)};wc.hInstance=instance_;wc.lpfnWndProc=PickerProc;wc.lpszClassName=L"SnippetTool.Picker";wc.hCursor=LoadCursorW(nullptr,IDC_ARROW);wc.hbrBackground=reinterpret_cast<HBRUSH>(COLOR_WINDOW+1);RegisterClassExW(&wc);picker_=CreateWindowExW(WS_EX_TOOLWINDOW|WS_EX_TOPMOST,wc.lpszClassName,L"スニペットを選択",WS_POPUP|WS_CAPTION|WS_SYSMENU,0,0,500,300,nullptr,nullptr,instance_,this);pickerList_=CreateWindowExW(WS_EX_CLIENTEDGE,L"LISTBOX",L"",WS_CHILD|WS_VISIBLE|WS_VSCROLL|LBS_NOTIFY|LBS_NOINTEGRALHEIGHT,8,8,468,246,picker_,reinterpret_cast<HMENU>(PickerList),instance_,nullptr);SendMessageW(pickerList_,WM_SETFONT,reinterpret_cast<WPARAM>(GetStockObject(DEFAULT_GUI_FONT)),TRUE);}
void App::ShowPicker(){if(pending_)return;if(IsWindowVisible(picker_)){HidePicker();return;}inputTarget_=GetForegroundWindow();if(!inputTarget_||inputTarget_==window_||inputTarget_==picker_)return;pickerItems_.clear();SendMessageW(pickerList_,LB_RESETCONTENT,0,0);for(const auto& item:settings_.snippets){if(!item.enabled)continue;pickerItems_.push_back(&item);const std::wstring label=FormatPickerItem(item);SendMessageW(pickerList_,LB_ADDSTRING,0,reinterpret_cast<LPARAM>(label.c_str()));}if(pickerItems_.empty()){MessageBeep(MB_ICONINFORMATION);SetStatus(L"選択できる有効なスニペットがありません。");return;}SendMessageW(pickerList_,LB_SETCURSEL,0,0);POINT point{};GetCursorPos(&point);RECT work{};SystemParametersInfoW(SPI_GETWORKAREA,0,&work,0);constexpr int width=500,height=300;const int x=std::clamp(point.x-width/2,work.left,work.right-width);const int y=std::clamp(point.y-height/2,work.top,work.bottom-height);SetWindowPos(picker_,HWND_TOPMOST,x,y,width,height,SWP_SHOWWINDOW);SetForegroundWindow(picker_);SetFocus(pickerList_);}
void App::HidePicker(){if(!IsWindowVisible(picker_))return;ShowWindow(picker_,SW_HIDE);pickerItems_.clear();if(inputTarget_&&IsWindow(inputTarget_))SetForegroundWindow(inputTarget_);}
void App::ChoosePickerItem(){const LRESULT selected=SendMessageW(pickerList_,LB_GETCURSEL,0,0);if(selected==LB_ERR||static_cast<size_t>(selected)>=pickerItems_.size())return;const Snippet* choice=pickerItems_[static_cast<size_t>(selected)];ShowWindow(picker_,SW_HIDE);pickerItems_.clear();BeginInput(choice);}
void App::BeginInput(const Snippet* snippet){if(!snippet||!inputTarget_||!IsWindow(inputTarget_)){pending_=nullptr;return;}pending_=snippet;SetForegroundWindow(inputTarget_);timerTicks_=0;if(!SetTimer(window_,INPUT_TIMER,10,nullptr))pending_=nullptr;}
LRESULT App::HandlePicker(UINT m,WPARAM p,LPARAM l){switch(m){case WM_COMMAND:if(LOWORD(p)==PickerList&&HIWORD(p)==LBN_DBLCLK){ChoosePickerItem();return 0;}break;case WM_CLOSE:HidePicker();return 0;case WM_ACTIVATE:if(LOWORD(p)==WA_INACTIVE&&IsWindowVisible(picker_)){ShowWindow(picker_,SW_HIDE);pickerItems_.clear();}break;}return DefWindowProcW(picker_,m,p,l);}
void App::Refresh(){ListView_DeleteAllItems(list_);for(size_t i=0;i<settings_.snippets.size();++i){const auto& s=settings_.snippets[i];LVITEMW row{LVIF_TEXT};row.iItem=static_cast<int>(i);row.pszText=const_cast<LPWSTR>(s.name.c_str());ListView_InsertItem(list_,&row);const auto formatted=FormatHotkey(s.hotkey);ListView_SetItemText(list_,row.iItem,1,const_cast<LPWSTR>(formatted.c_str()));ListView_SetItemText(list_,row.iItem,2,const_cast<LPWSTR>(s.enabled?L"有効":L"無効"));const wchar_t* registration=!s.enabled?L"無効":hotkeys_&&hotkeys_->IsRegistered(s.id)?L"登録済み":L"登録失敗";ListView_SetItemText(list_,row.iItem,3,const_cast<LPWSTR>(registration));}}
void App::Select(int i){selected_=i;if(i<0||i>=static_cast<int>(settings_.snippets.size())){SetWindowTextW(name_,L"");SetWindowTextW(body_,L"");SendMessageW(hotkey_,HKM_SETHOTKEY,0,0);Button_SetCheck(win_,BST_UNCHECKED);Button_SetCheck(enabled_,BST_CHECKED);return;}const auto& s=settings_.snippets[i];SetWindowTextW(name_,s.name.c_str());SetWindowTextW(body_,s.body.c_str());SendMessageW(hotkey_,HKM_SETHOTKEY,ControlHotkey(s.hotkey),0);Button_SetCheck(win_,(ModifierMask(s.hotkey)&8)?BST_CHECKED:BST_UNCHECKED);Button_SetCheck(enabled_,s.enabled?BST_CHECKED:BST_UNCHECKED);}
void App::SaveCurrent(){if(loadErrorLocked_){SetStatus(L"破損設定を保護中のため保存できません。");return;}const bool adding=selected_<0;const int nl=GetWindowTextLengthW(name_),bl=GetWindowTextLengthW(body_);std::wstring n(static_cast<size_t>(nl)+1,L'\0'),b(static_cast<size_t>(bl)+1,L'\0');GetWindowTextW(name_,n.data(),nl+1);GetWindowTextW(body_,b.data(),bl+1);n.resize(nl);b.resize(bl);auto key=DomainHotkey(static_cast<WORD>(SendMessageW(hotkey_,HKM_GETHOTKEY,0,0)));if(Button_GetCheck(win_)==BST_CHECKED)key.modifiers.push_back(Modifier::Win);Snippet candidate{adding?Guid():settings_.snippets[selected_].id,n,b,key,Button_GetCheck(enabled_)==BST_CHECKED};const auto error=adding?service_->Add(candidate):service_->Update(settings_.snippets[selected_].id,candidate);if(!error.empty()){SetStatus(error);return;}if(adding)selected_=static_cast<int>(settings_.snippets.size())-1;Refresh();SetStatus(L"保存しました。");}
void App::RemoveCurrent(){if(loadErrorLocked_){SetStatus(L"破損設定を保護中のため削除できません。");return;}if(selected_<0)return;if(MessageBoxW(window_,(L"「"+settings_.snippets[selected_].name+L"」を削除しますか？").c_str(),L"確認",MB_YESNO|MB_ICONQUESTION)!=IDYES)return;const auto error=service_->Remove(settings_.snippets[selected_].id);if(!error.empty()){SetStatus(error);return;}selected_=-1;Refresh();Select(-1);}
void App::UpdateStartup(){if(loadErrorLocked_){Button_SetCheck(startup_,settings_.startupEnabled?BST_CHECKED:BST_UNCHECKED);SetStatus(L"破損設定を保護中のため変更できません。");return;}const bool previous=settings_.startupEnabled,desired=Button_GetCheck(startup_)==BST_CHECKED;std::wstring error;if(TestRoot().empty())error=desired?startupManager_.Enable(ExePath()):startupManager_.Disable(ExePath());if(!error.empty()){Button_SetCheck(startup_,previous?BST_CHECKED:BST_UNCHECKED);SetStatus(error);return;}settings_.startupEnabled=desired;error=repository_->Save(settings_);if(!error.empty()){settings_.startupEnabled=previous;if(TestRoot().empty()){const auto ignored=previous?startupManager_.Enable(ExePath()):startupManager_.Disable(ExePath());(void)ignored;}Button_SetCheck(startup_,previous?BST_CHECKED:BST_UNCHECKED);SetStatus(error);return;}SetStatus(L"スタートアップ設定を更新しました。");}
void App::UpdatePickerHotkey(){if(loadErrorLocked_){SendMessageW(pickerHotkey_,HKM_SETHOTKEY,ControlHotkey(settings_.pickerHotkey),0);Button_SetCheck(pickerWin_,(ModifierMask(settings_.pickerHotkey)&8)?BST_CHECKED:BST_UNCHECKED);SetStatus(L"破損設定を保護中のため変更できません。");return;}Hotkey desired=DomainHotkey(static_cast<WORD>(SendMessageW(pickerHotkey_,HKM_GETHOTKEY,0,0)));if(Button_GetCheck(pickerWin_)==BST_CHECKED)desired.modifiers.push_back(Modifier::Win);AppSettings next=settings_;next.pickerHotkey=desired;if(const auto errors=ValidateSettings(next);!errors.empty()){SetStatus(errors.front());return;}const Hotkey previous=settings_.pickerHotkey;const bool wasRegistered=pickerHotkeyRegistered_;if(wasRegistered)UnregisterHotKey(window_,PICKER_HOTKEY_ID);pickerHotkeyRegistered_=RegisterHotKey(window_,PICKER_HOTKEY_ID,NativeModifiers(desired),desired.virtualKey)!=FALSE;if(!pickerHotkeyRegistered_){if(wasRegistered)pickerHotkeyRegistered_=RegisterHotKey(window_,PICKER_HOTKEY_ID,NativeModifiers(previous),previous.virtualKey)!=FALSE;SetStatus(FormatHotkey(desired)+L" を登録できません (HOTKEY-REG-001)。");return;}if(const auto error=repository_->Save(next);!error.empty()){UnregisterHotKey(window_,PICKER_HOTKEY_ID);pickerHotkeyRegistered_=wasRegistered&&RegisterHotKey(window_,PICKER_HOTKEY_ID,NativeModifiers(previous),previous.virtualKey)!=FALSE;SetStatus(error);return;}settings_=std::move(next);SetStatus(L"ミニ画面表示キーを "+FormatHotkey(settings_.pickerHotkey)+L" に更新しました。");}
void App::SetStatus(const std::wstring& text){SetWindowTextW(status_,text.c_str());if(!logger_||text.empty())return;const wchar_t* ids[]={L"CFG-LOAD-001",L"CFG-SAVE-001",L"HOTKEY-REG-001",L"INPUT-SEND-001",L"STARTUP-REG-001",L"TRAY-ADD-001"};std::wstring event=L"UI-STATUS";for(const auto* id:ids)if(text.find(id)!=std::wstring::npos){event=id;break;}logger_->Write(event==L"UI-STATUS"?LogLevel::Info:LogLevel::Error,event,L"STATUS-CHANGED",GetLastError());}
void App::AddTray(){tray_.hWnd=window_;tray_.uID=1;tray_.uFlags=NIF_MESSAGE|NIF_ICON|NIF_TIP;tray_.uCallbackMessage=WM_TRAY;tray_.hIcon=LoadIconW(nullptr,IDI_APPLICATION);wcscpy_s(tray_.szTip,L"スニペットツール");Shell_NotifyIconW(NIM_ADD,&tray_);tray_.uVersion=NOTIFYICON_VERSION_4;Shell_NotifyIconW(NIM_SETVERSION,&tray_);}
void App::Show(){ShowWindow(window_,SW_RESTORE);SetForegroundWindow(window_);}
LRESULT App::Handle(UINT m,WPARAM p,LPARAM l){if(m==showMessage){Show();return 0;}if(m==taskbarMessage){AddTray();return 0;}switch(m){case WM_COMMAND:switch(LOWORD(p)){case NewItem:selected_=-1;Select(-1);break;case Save:SaveCurrent();break;case Remove:RemoveCurrent();break;case Startup:if(HIWORD(p)==BN_CLICKED)UpdateStartup();break;case SavePickerHotkey:if(HIWORD(p)==BN_CLICKED)UpdatePickerHotkey();break;}break;
 case WM_NOTIFY:if(reinterpret_cast<NMHDR*>(l)->idFrom==List&&reinterpret_cast<NMHDR*>(l)->code==LVN_ITEMCHANGED){const int i=ListView_GetNextItem(list_,-1,LVNI_SELECTED);if(i>=0&&i!=selected_)Select(i);}break;
 case WM_HOTKEY:if(static_cast<int>(p)==PICKER_HOTKEY_ID){ShowPicker();break;}if(pending_)break;inputTarget_=GetForegroundWindow();if(inputTarget_==window_||inputTarget_==picker_)break;BeginInput(hotkeys_->Resolve(static_cast<int>(p)));break;
 case WM_TIMER:if(p==INPUT_TIMER){++timerTicks_;const bool held=(GetAsyncKeyState(VK_CONTROL)&0x8000)||(GetAsyncKeyState(VK_MENU)&0x8000)||(GetAsyncKeyState(VK_SHIFT)&0x8000)||(GetAsyncKeyState(VK_LWIN)&0x8000)||(GetAsyncKeyState(VK_RWIN)&0x8000);if(!held||timerTicks_>=50){KillTimer(window_,INPUT_TIMER);if(!held&&GetForegroundWindow()==inputTarget_&&pending_)SetStatus(EmitText(pending_->body));pending_=nullptr;}}break;
 case WM_SIZE:if(p==SIZE_MINIMIZED){ShowWindow(window_,SW_HIDE);SetStatus(L"タスクトレイで実行中です。");return 0;}break;
 case WM_TRAY:{const UINT event=LOWORD(l);if(event==NIN_SELECT||event==WM_LBUTTONUP||event==WM_LBUTTONDBLCLK)Show();else if(event==WM_CONTEXTMENU||event==WM_RBUTTONUP){HMENU menu=CreatePopupMenu();AppendMenuW(menu,MF_STRING,1,L"メニュー");AppendMenuW(menu,MF_STRING,2,L"終了");POINT pt{};GetCursorPos(&pt);SetForegroundWindow(window_);const int command=TrackPopupMenu(menu,TPM_RETURNCMD|TPM_RIGHTBUTTON,pt.x,pt.y,0,window_,nullptr);DestroyMenu(menu);if(command==1)Show();else if(command==2)DestroyWindow(window_);}}break;
 case WM_CLOSE:ShowWindow(window_,SW_HIDE);SetStatus(L"タスクトレイで実行中です。");return 0;case WM_DESTROY:KillTimer(window_,INPUT_TIMER);if(pickerHotkeyRegistered_)UnregisterHotKey(window_,PICKER_HOTKEY_ID);hotkeys_->Clear();Shell_NotifyIconW(NIM_DELETE,&tray_);PostQuitMessage(0);return 0;}return DefWindowProcW(window_,m,p,l);}
}
int WINAPI wWinMain(_In_ HINSTANCE instance,_In_opt_ HINSTANCE,_In_ PWSTR,_In_ int show){try{showMessage=RegisterWindowMessageW(L"SnippetTool.Show");taskbarMessage=RegisterWindowMessageW(L"TaskbarCreated");SingleInstance single(MutexName());if(!single.Acquire()){SendMessageTimeoutW(HWND_BROADCAST,showMessage,0,0,SMTO_ABORTIFHUNG,1000,nullptr);return 0;}App app;return app.Run(instance,show);}catch(...){MessageBoxW(nullptr,L"起動中に予期しないエラーが発生しました。",L"スニペットツール",MB_OK|MB_ICONERROR);return 1;}}
